Use openssl instead of xxd for moshrc

diff --git a/moshrc b/moshrc
--- a/moshrc
+++ b/moshrc
@@ -15,24 +15,24 @@ function moshrc() {
             exit 1
         fi
         mosh "$@" -- /bin/bash -c "
-            command -v xxd >/dev/null 2>&1 || { printf >&2 \"sshrc requires xxd to be installed on the server, but it's not. Aborting.\\n\"; exit 1; }
+            command -v openssl >/dev/null 2>&1 || { printf >&2 \"sshrc requires openssl to be installed on the server, but it's not. Aborting.\\n\"; exit 1; }
             if [ -e /etc/motd ]; then cat /etc/motd; fi
             if [ -e /etc/update-motd.d ]; then run-parts /etc/update-motd.d/; fi
             export SSHHOME=\$(mktemp -d -t .$(whoami).sshrc.XXXX)
             export SSHRCCLEANUP=\$SSHHOME
             trap \"rm -rf \$SSHRCCLEANUP; exit\" 0
-            printf %s '$(cat $0 | xxd -p)' | xxd -p -r > \$SSHHOME/moshrc
+            printf %s '$(<"$0" openssl enc -base64)' | openssl enc -base64 -d > \$SSHHOME/moshrc
             chmod +x \$SSHHOME/moshrc
 
-            printf %s '$( cat << 'EOF' | xxd -p
+            printf %s '$( openssl enc -base64 << 'EOF'
 if [ -e /etc/bash.bashrc ]; then source /etc/bash.bashrc; fi
 if [ -e ~/.bashrc ]; then source ~/.bashrc; fi
 source $SSHHOME/.sshrc;
 export PATH=$PATH:$SSHHOME
 EOF
-)' | xxd -p -r > \$SSHHOME/sshrc.bashrc
+)' | openssl enc -base64 -d > \$SSHHOME/sshrc.bashrc
 
-            printf %s '$( cat << 'EOF' | xxd -p
+            printf %s '$( openssl enc -base64 << 'EOF'
 #!/usr/bin/env bash
 exec bash --rcfile <(printf %s '
 if [ -e /etc/bash.bashrc ]; then source /etc/bash.bashrc; fi
@@ -41,10 +41,10 @@ source '$SSHHOME'/.sshrc;
 export PATH=$PATH:'$SSHHOME'
 ') "$@"
 EOF
-)' | xxd -p -r > \$SSHHOME/bashsshrc
+)' | openssl enc -base64 -d > \$SSHHOME/bashsshrc
             chmod +x \$SSHHOME/bashsshrc
 
-            printf %s '$(tar czf - -h -C $SSHHOME $files | xxd -p)' | xxd -p -r | tar mxzf - -C \$SSHHOME
+            printf %s '$(tar czf - -h -C $SSHHOME $files | openssl enc -base64)' | openssl enc -base64 -d | tar mxzf - -C \$SSHHOME
             export SSHHOME=\$SSHHOME
             bash --rcfile \$SSHHOME/sshrc.bashrc
             "
@@ -53,7 +53,7 @@ EOF
     fi
 }
 if [ "$1" ]; then
-    command -v xxd >/dev/null 2>&1 || { printf >&2 "sshrc requires xxd to be installed locally, but it's not. Aborting.\\n"; exit 1; }
+    command -v openssl >/dev/null 2>&1 || { printf >&2 "sshrc requires openssl to be installed locally, but it's not. Aborting.\\n"; exit 1; }
     moshrc "$@"
 else
     mosh
