Remove all usages of $'' and echo

diff --git a/moshrc b/moshrc
--- a/moshrc
+++ b/moshrc
@@ -11,20 +11,20 @@ function moshrc() {
         fi
         SIZE=$(tar cfz - -h -C $SSHHOME $files | wc -c)
         if [ $SIZE -gt 65536 ]; then
-            echo >&2 $'.sshrc.d and .sshrc files must be less than 64kb\ncurrent size: '$SIZE' bytes'
+            printf >&2 '.sshrc.d and .sshrc files must be less than 64kb\ncurrent size: %s bytes\n' "$SIZE"
             exit 1
         fi
         mosh "$@" -- /bin/bash -c "
-            command -v xxd >/dev/null 2>&1 || { echo >&2 \"sshrc requires xxd to be installed on the server, but it's not. Aborting.\"; exit 1; }
+            command -v xxd >/dev/null 2>&1 || { printf >&2 \"sshrc requires xxd to be installed on the server, but it's not. Aborting.\\n\"; exit 1; }
             if [ -e /etc/motd ]; then cat /etc/motd; fi
             if [ -e /etc/update-motd.d ]; then run-parts /etc/update-motd.d/; fi
             export SSHHOME=\$(mktemp -d -t .$(whoami).sshrc.XXXX)
             export SSHRCCLEANUP=\$SSHHOME
             trap \"rm -rf \$SSHRCCLEANUP; exit\" 0
-            echo $'$(cat $0 | xxd -p)' | xxd -p -r > \$SSHHOME/moshrc
+            printf %s '$(cat $0 | xxd -p)' | xxd -p -r > \$SSHHOME/moshrc
             chmod +x \$SSHHOME/moshrc
 
-            echo $'$( cat << 'EOF' | xxd -p
+            printf %s '$( cat << 'EOF' | xxd -p
 if [ -e /etc/bash.bashrc ]; then source /etc/bash.bashrc; fi
 if [ -e ~/.bashrc ]; then source ~/.bashrc; fi
 source $SSHHOME/.sshrc;
@@ -32,9 +32,9 @@ export PATH=$PATH:$SSHHOME
 EOF
 )' | xxd -p -r > \$SSHHOME/sshrc.bashrc
 
-            echo $'$( cat << 'EOF' | xxd -p
+            printf %s '$( cat << 'EOF' | xxd -p
 #!/usr/bin/env bash
-exec bash --rcfile <(echo '
+exec bash --rcfile <(printf %s '
 if [ -e /etc/bash.bashrc ]; then source /etc/bash.bashrc; fi
 if [ -e ~/.bashrc ]; then source ~/.bashrc; fi
 source '$SSHHOME'/.sshrc;
@@ -44,16 +44,16 @@ EOF
 )' | xxd -p -r > \$SSHHOME/bashsshrc
             chmod +x \$SSHHOME/bashsshrc
 
-            echo $'$(tar czf - -h -C $SSHHOME $files | xxd -p)' | xxd -p -r | tar mxzf - -C \$SSHHOME
+            printf %s '$(tar czf - -h -C $SSHHOME $files | xxd -p)' | xxd -p -r | tar mxzf - -C \$SSHHOME
             export SSHHOME=\$SSHHOME
             bash --rcfile \$SSHHOME/sshrc.bashrc
             "
     else
-        echo "No such file: $SSHHOME/.sshrc"
+        printf 'No such file: %s\n' "$SSHHOME/.sshrc"
     fi
 }
 if [ "$1" ]; then
-    command -v xxd >/dev/null 2>&1 || { echo >&2 "sshrc requires xxd to be installed locally, but it's not. Aborting."; exit 1; }
+    command -v xxd >/dev/null 2>&1 || { printf >&2 "sshrc requires xxd to be installed locally, but it's not. Aborting.\\n"; exit 1; }
     moshrc "$@"
 else
     ssh
diff --git a/sshrc b/sshrc
--- a/sshrc
+++ b/sshrc
@@ -8,7 +8,7 @@ function sshrc() {
         fi
         SIZE=$(tar cfz - -h -C $SSHHOME $files | wc -c)
         if [ $SIZE -gt 65536 ]; then
-            echo >&2 $'.sshrc.d and .sshrc files must be less than 64kb\ncurrent size: '$SIZE' bytes'
+            printf >&2 '.sshrc.d and .sshrc files must be less than 64kb\ncurrent size: %s bytes\n' "$SIZE"
             exit 1
         fi
         if [ -z "$CMDARG" -a ! -e ~/.sshrc.d/.hushlogin ]; then
@@ -23,15 +23,15 @@ function sshrc() {
             WELCOME_MSG=""
         fi
         ssh -t "$DOMAIN" $SSHARGS "
-            command -v openssl >/dev/null 2>&1 || { echo >&2 \"sshrc requires openssl to be installed on the server, but it's not. Aborting.\"; exit 1; }
+            command -v openssl >/dev/null 2>&1 || { printf >&2 \"sshrc requires openssl to be installed on the server, but it's not. Aborting.\\n\"; exit 1; }
             $WELCOME_MSG
             export SSHHOME=\$(mktemp -d -t .$(whoami).sshrc.XXXX)
             export SSHRCCLEANUP=\$SSHHOME
             trap \"rm -rf \$SSHRCCLEANUP; exit\" 0
-            echo $'"$(cat "$0" | openssl enc -base64)"' | tr -s ' ' $'\n' | openssl enc -base64 -d > \$SSHHOME/sshrc
+            printf %s '"$(cat "$0" | openssl enc -base64)"' | tr -s ' ' '\\n' | openssl enc -base64 -d > \$SSHHOME/sshrc
             chmod +x \$SSHHOME/sshrc
 
-            echo $'"$( cat << 'EOF' | openssl enc -base64
+            printf %s '"$( cat << 'EOF' | openssl enc -base64
                 if [ -r /etc/profile ]; then source /etc/profile; fi
                 if [ -r ~/.bash_profile ]; then source ~/.bash_profile
                 elif [ -r ~/.bash_login ]; then source ~/.bash_login
@@ -40,11 +40,11 @@ function sshrc() {
                 export PATH=$PATH:$SSHHOME
                 source $SSHHOME/.sshrc;
 EOF
-                )"' | tr -s ' ' $'\n' | openssl enc -base64 -d > \$SSHHOME/sshrc.bashrc
+                )"' | tr -s ' ' '\\n' | openssl enc -base64 -d > \$SSHHOME/sshrc.bashrc
 
-            echo $'"$( cat << 'EOF' | openssl enc -base64
+            printf %s '"$( cat << 'EOF' | openssl enc -base64
 #!/usr/bin/env bash
-                exec bash --rcfile <(echo '
+                exec bash --rcfile <(printf %s\\n '
                 [ -r /etc/profile ] && source /etc/profile
                 if [ -r ~/.bash_profile ]; then source ~/.bash_profile
                 elif [ -r ~/.bash_login ]; then source ~/.bash_login
@@ -54,16 +54,16 @@ EOF
                 export PATH=$PATH:'$SSHHOME'
                 ') "$@"
 EOF
-                )"' | tr -s ' ' $'\n' | openssl enc -base64 -d > \$SSHHOME/bashsshrc
+                )"' | tr -s ' ' '\\n' | openssl enc -base64 -d > \$SSHHOME/bashsshrc
             chmod +x \$SSHHOME/bashsshrc
 
-            echo $'"$(tar czf - -h -C $SSHHOME $files | openssl enc -base64)"' | tr -s ' ' $'\n' | openssl enc -base64 -d | tar mxzf - -C \$SSHHOME
+            printf %s '"$(tar czf - -h -C $SSHHOME $files | openssl enc -base64)"' | tr -s ' ' '\\n' | openssl enc -base64 -d | tar mxzf - -C \$SSHHOME
             export SSHHOME=\$SSHHOME
-            echo \"$CMDARG\" >> \$SSHHOME/sshrc.bashrc
+            printf %s\\\\n \"$CMDARG\" >> \$SSHHOME/sshrc.bashrc
             bash --rcfile \$SSHHOME/sshrc.bashrc
             "
     else
-        echo "No such file: $SSHHOME/.sshrc" >&2
+        printf 'No such file: %s\n' "$SSHHOME/.sshrc" >&2
         exit 1
     fi
 }
@@ -79,7 +79,7 @@ function sshrc_parse() {
         if [ -z "$DOMAIN" ]; then
          DOMAIN="$1"
         else
-          local SEMICOLON=$([[ "$@" = *[![:space:]]* ]] && echo '; ')
+          local SEMICOLON=$([[ "$@" = *[![:space:]]* ]] && printf '; ')
           CMDARG="$@$SEMICOLON exit"
           return;
         fi
@@ -92,6 +92,6 @@ function sshrc_parse() {
   fi
 }
 
-command -v openssl >/dev/null 2>&1 || { echo >&2 "sshrc requires openssl to be installed locally, but it's not. Aborting."; exit 1; }
+command -v openssl >/dev/null 2>&1 || { printf >&2 "sshrc requires openssl to be installed locally, but it's not. Aborting.\\n"; exit 1; }
 sshrc_parse "$@"
 sshrc
